include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    avoid_print: error
    invalid_use_of_visible_for_testing_member: error

linter:
  rules:
    always_declare_return_types: true
    avoid_dynamic_calls: true
    directives_ordering: true
    prefer_final_locals: true
    sort_constructors_first: true
    unawaited_futures: true
